### ISSUE TITLE
Crash after switching users

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1976]
## What did you do?
Switched users in my chat application

## What did you expect to happen?
Normal operation

## What happened instead?
The app crashed:
`StreamChat/CoreDataLazy.swift:49: Fatal error: Persistent store identifier changed. This means the persistent store was reloaded, but a reference to a model was kept in memory.
This can happen if a snapshot of data (ChatMessage, ChatUser, ChatChannel) was kept in memory after Database is wiped (for example, in the event of logging in with a new user).
If you're sure there are no references to models from another session, please report this stack trace to Stream iOS Team.
2022-05-04 14:06:43.147 [ERROR] [main] [CoreDataLazy.swift:48] [wrappedValue] > Persistent store identifier changed. This means the persistent store was reloaded, but a reference to a model was kept in memory.
This can happen if a snapshot of data (ChatMessage, ChatUser, ChatChannel) was kept in memory after Database is wiped (for example, in the event of logging in with a new user).
If you're sure there are no references to models from another session, please report this stack trace to Stream iOS Team.
2022-05-04 14:06:43.147339-0500 StreamSwitchUsers[37154:10162493] StreamChat/CoreDataLazy.swift:49: Fatal error: Persistent store identifier changed. This means the persistent store was reloaded, but a reference to a model was kept in memory.
This can happen if a snapshot of data (ChatMessage, ChatUser, ChatChannel) was kept in memory after Database is wiped (for example, in the event of logging in with a new user).
If you're sure there are no references to models from another session, please report this stack trace to Stream iOS Team.
`

## GetStream Environment
**GetStream Chat version:** 4.12.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
See attached sample project:
[StreamSwitchUsers.zip](https://github.com/GetStream/stream-chat-swift/files/8626465/StreamSwitchUsers.zip)

Steps to reproduce:
- Run sample project
- Login as user1
- Select chat channel to view it
- Send a chat message
- Back actions to initial screen
- Logout
- Login as user2
- App crashes with above info

**Comment by evsaev** [comment]
Hey @srgray 👋 

Thanks for reaching us!

Would you try to upgrade to [4.14.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.14.0) SDK version and see if it solves the issue?

It contains multiple stability fixes including the PR that's supposed to fix the crash you're facing with: 
https://github.com/GetStream/stream-chat-swift/pull/1926

Looking forward to hearing back!

Best,
Pavel

**Comment by srgray** [comment]
After upgrading to 4.14.0 SDK, the crash does not occur (👍 ) but I do get this behavior:
- Run sample project
- Login as user1
- Select chat channel to view it
- Send a chat message
- Back actions to initial screen
- Logout
- Login as user2
- Tap to enter chat channel
- Chat channel is not shown and console logs: 
```2022-05-05 06:06:05.346 [ERROR] [main] [ChatChannelListVC.swift:357] [getChannel(at:)] > Assert failed: Accessing an index that is not present in the data source```

**Comment by evsaev** [comment]
Hey @srgray 👋 

When the chat client is connected with another user, the `ChatChannelListVC` should be recreated in case the underlying channel query involves a condition with `currentUserId`. Otherwise, the list will be showing channels for the previous user.

Would you try to recreate the channel list VC and check that the error is gone?

Thanks! 

Best,  
Pavel

**Comment by srgray** [comment]
@evsaev OK, yes, when I recreate the channel list VC, that error is now gone. Thanks for you help on this!
